import Head from "next/head";

import Hero from "../components/hero/Hero";
import ImageTextRight from "../components/imageTextRight/ImageTextRight";
import ImageTextLeft from "../components/imageTextLeft/ImageTextLeft";

import clinicImage from "../public/our-clinic.jpg";
import staffImage from "../public/our-staff.jpg";
import healthImage from "../public/health-myself.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Lincoln Medical Center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Hero
        title="Lincoln Medical Centre"
        subTitle="Family Health Organization"
        btnText="HealthMyself Login"
        btnLink="https://portal.healthmyself.net/lincolnmedicalcentre/"
      />
      <ImageTextRight
        image={clinicImage}
        bgColor="#FFF"
        altText="our clinic"
        title="Our Clinic"
        text="Lincoln Medical Centre is comprised of a team of family physicians, nurses and support staff that work together to ensure that excellent quality patient care is provided in a respectful and compassionate environment."
        btnText="Learn More"
        btnLink="/mission/"
        targetValue="_self"
      />
      <ImageTextLeft
        image={staffImage}
        altText="Our Staff"
        title="Our Staff"
        text="Lincoln Medical Centre is comprised of a team of family
        physicians, nurses and support staff that work together to
        ensure that excellent quality patient care is provided in a
        respectful and compassionate environment."
        btnText="View Staff"
        btnLink="/team/"
      />
      <ImageTextRight
        image={healthImage}
        bgColor="#FFF"
        altText="HealthMyself"
        title="HealthMyself"
        text="
        Health Myself Patient Portal - Health Myself is an online portal
        available to provide patients with easier access to their
        healthcare. Health Myself allows your doctor to securely send
        results, reports and messages directly to your email. Health
        Myself also allows patients to book appointments with their
        doctor easily online.
      "
        btnText="HealthMyself Login"
        btnLink="https://portal.healthmyself.net/lincolnmedicalcentre/"
        targetValue="_blank"
      />
    </>
  );
}
